version: '3.7'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8448:8448
    volumes:
      - ./conf_nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # is it really required?
      - ./conf_nginx/dhparam:/etc/nginx/dhparam:ro
      - ./data_nginx:/usr/share/nginx/html:ro
      - ./data_letsencrypt:/etc/letsencrypt:ro
      - ./log_nginx:/var/log/nginx
    networks:
      - matrix-server
    command: "/bin/sh -c 'while :; do sleep 36h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: always
    volumes:
      - ./data_nginx:/usr/share/nginx/html:ro
      - ./data_letsencrypt:/etc/letsencrypt
      - ./log_letsencrypt:/var/log/letsencrypt
    networks:
      - matrix-server
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  postgresql:
    image: postgres:15-bullseye
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./data_postgresql:/var/lib/postgresql/data
    networks:
      - matrix-server
    secrets:
      - db_password

  synapse:
    image: matrixdotorg/synapse:v1.72.0
    container_name: synapse
    ports:
      - 8008:8008
    environment:
      SYNAPSE_SERVER_NAME: 'kuroan.co'
      SYNAPSE_REPORT_STATS: 'no'
    volumes:
      - ./data_synapse:/data
    networks:
      - matrix-server
    depends_on:
      - nginx
      - postgresql

secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  matrix-server:
    external: true
